### PR TITLE
Support alternate transitions for belt-items

### PR DESCRIPTION
**Pull request by Xcelled**
When I'm working with belts, I very rarely want to grab a different tier of belt. I much more frequently want to change from a belt to a splitter, or something else within the same tier.

With that in mind, I added support for three new transition approaches for belts for a total of four:

	- Tier (belt <-> fast belt <-> express belt)
	- Category (belt <-> underground <-> splitter)
	- Tier then Category (belt <-> fast belt <-> express belt <-> underground <-> fast underground ...)
	- Category then Tier (belt <-> underground <-> splitter <-> fast belt <-> fast underground ...)

The player can choose the transition strategy via a setting. It's implemented in a mod-agnostic way, so it should work out of the box with any mods that add belt-like items (eg bobs, ~~miniloaders~~ [edit: not actually a belt item], etc), though I haven't tested this with anything other than vanilla. This is achieved by grouping belts by their speed to determine the tier, and by using the item's `order` property to determine how to order items of the same tier.

Vanilla loaders are omitted unless cheat mode is on, since there's no legitimate way to get them.

### CODE REVIEW

**Comment by raiguard** [comment]
Thank you for the contribution! However, it doesn't seem to work correctly in the following cases:

- In `tiers then categories` mode, it will scroll up to the first loader, but then stop without letting me scroll to the other loader types
- It doesn't appear to work with miniloader

If you can fix these, then I'll be happy to merge it. Thank you again!

**Comment by Xcelled** [comment]
The vanilla loader issue is because vanilla doesn't set the next upgrade info for the loaders :( I'll probably solve this by adding some default overrides, unless you have an alternate approach?

I'll have to take a look at mini-loaders and see what's gone wrong there. According the the prototypes, the loaders should be returned with the rest of the belt entities.

**Comment by Xcelled** [comment]
So the issue with miniloaders is that the miniloader belt entities are "fake" entities returned by mining. No items can build them, so they're ignored. The miniloaders that are built when you place an item are actually categorized as inserters, not belts.

I'm not sure if or how the mod should re-categorize these - it seems like a more involved task that's orthogonal to this PR.

**Comment by raiguard** [comment]
While I like the idea of this PR, the reason why I never merged it was because I don't really have a problem without it. There are 100 hotbar slots now so reserving four of them for belt things isn't that bad. And the current implementation is super simple and elegant. :)

**Pull request closed without merging**
